#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=03:00:00
#PBS -N fastqc
#PBS -j oe
#PBS -q short
#PBS -M sleiman.bassim@stonybrook.edu
#PBS -m abe
#PBS -V

# DONT CHANGE #
###############
scratch=/gpfs/scratch/ballam
home=/gpfs/home/ballam
pbs=$(echo $PBS_JOBID | cut -f 1 -d '.')
reads=$scratch/ganglia/raw.reads
output=$scratch/ganglia/qc

mkdir -p $output

fastqc=$home/FastQC/fastqc

for s in br gg; do
    for i in {1..24}; do
        for j in {1..2}; do

zcat $reads/$s/$s.$i.R$j.fastq.gz | $fastqc $reads/$s/$s.$i.R$j.fastq.gz --outdir=$output

        done
    done
done


cd $output
source activate bassim
multiqc .
