#!/bin/bash
#PBS -q normal
#PBS -l nodes=4:ppn=16:native
#PBS -l walltime=01:00:00
#PBS -N blastnVFDB.A
#PBS -e blastnVFDB.A.err
#PBS -A sun108
#PBS -M sleiman.bassim@stonybrook.edu
#PBS -m abe
#PBS -V

export PATH="$PATH:/home/silo/blast/bin"
export BLASTDB="/oasis/projects/nsf/sun108/bassem/db/vfdb/vfnt"
oasis=/oasis/projects/nsf/sun108

blastn -query ${oasis}/silo/nodule/assembled/A.assembl.QPXgv5.fasta \
-db vfnt \
-outfmt " 7 qseqid qlen sseqid slen qstart qend sstart send evalue bitscore length pident nident mismatch gaps staxids sscinames " \
-max_target_seqs 10 \
-num_threads 16 \
-out ${oasis}/silo/nodule/blast/A.blastn.vfnt.txt
