#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=04:00:00
#PBS -N mmetsp
#PBS -q short
#PBS -V

set -eux

# Files _CHANGE_ string nr
blast=blastn
db=mmetsp0098
maxSeq=10
file=Trinity.fasta
transcriptome=A

scratch=/gpfs/scratch/ballam
home=/gpfs/home/ballam
project=$scratch/nodule/qpx-analysis/trinity/trinity_out_dir_$transcriptome

#tophit=$home/trinityrnaseq-2.1.1/util/analyze_blastPlus_topHit_coverage.pl

# DONT CHANGE #
# blast libraries
export PATH="$PATH:/gpfs/home/ballam/ncbi-blast-2.6.0+/bin"
export BLASTDB="/gpfs/scratch/ballam/db/swissprot"
# supercomputing power
pbs=$(echo $PBS_JOBID | cut -f 1 -d '.')
nthreads=$(expr 2 \* 16)

query=$project/$file
output=$project/blast/$transcriptome.$blast.$db.$pbs.txt

mkdir -p $project/blast

## Full blast
time=$home/time
jobid=$blast.$db
start=$(date); echo "Job started at: $start" > $time/$jobid.$pbs.time

cd $scratch/db/$db

$blast -query $query -db $db -outfmt " 7 qseqid qlen sseqid slen qstart qend sstart send evalue bitscore length pident nident mismatch gaps " -max_target_seqs $maxSeq -num_threads $nthreads -out $output

end=$(date); echo "Job ended at: $end" >> $time/$jobid.$pbs.time

#perl $tophit \
#$project/$file.$db.$ev.outfmt$n \
#$scratch/$extra/$file.$exe \
#$scratch/db/$db/$db \
#>& $project/$file.$db.$ev.tophit
