#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=00:10:00
#PBS -N diamond
#PBS -j oe
#PBS -q debug
#PBS -M sleiman.bassim@stonybrook.edu
#PBS -m abe
#PBS -V

## (1) index any protein fasta file first with diamond makedb
## (2) queries must be NUCLEOTIDE for blastx

# DONT CHANGE #
###############
scratch=/gpfs/scratch/ballam
home=/gpfs/home/ballam
pbs=$(echo $PBS_JOBID | cut -f 1 -d '.')

# Files _CHANGE_
db=martia
blast=blastx
maxseq=10

#project=$scratch/ganglia
query=$(find $scratch -maxdepth 4 -name "Trinit*GG.fasta" | egrep "para.*1")
output=$query.$db.$blast.diamond.$pbs
tmp=$(dirname $query)/tmp_$pbs

mkdir -p $tmp

# blast libraries
diamond=/gpfs/home/ballam/diamond.0.7/diamond
export PATH="$PATH:/gpfs/home/ballam/ncbi-blast-2.2.31+/bin"
export BLASTDB="/gpfs/scratch/ballam/db/$db"

## Full blastx
time=$home/time
jobid=$file.$db
start=$(date); echo "Job started at: $start" > $time/$jobid.$pbs.time

cd $scratch/db/$db

$diamond $blast -d $db -q $query -a $output -t $tmp -k $maxseq
$diamond view -a $output -f tab -o $output.txt
rm $output.daa
rm -r $tmp

end=$(date); echo "Job ended at: $end" >> $time/$jobid.$pbs.time
