#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=01:00:00
#PBS -N networks
#PBS -q short
#PBS -V
#PBS -M sleiman.bassim@stonybrook.edu
#PBS -j oe
#PBS -m abe

# IACS directories
scratch=/gpfs/scratch/ballam
home=/gpfs/home/ballam
pbs=$(echo $PBS_JOBID | cut -f1 -d '.')

# Files _CHANGE_
p=4
c=2
#_P=6
#_T=01
matrix=tissue
_COR=pearson.average
_DIR=$scratch/ganglia/trinity/trinity_out_dir_00000
file=DESeq2.eXpress.$matrix.p$p.c$c*
log=$_DIR/$file/diffExpr.P1e-${p}_C${c}.matrix.log2.dat
output=$_DIR/networks/$pbs
mkdir -p $output

time=$home/time
jobid=$pbs.R.networks
start=$(date); echo "Job started at: $start" > $time/$jobid.time

cd $output
cp $log $output
cp $_DIR/*id2description* $output
cp $home/script*/convertMatrix2graph.R $output

R CMD BATCH $home/script*/weighted.nets.R

end=$(date); echo "Job ended at: $end" >> $time/$jobid.time

